### ISSUE TITLE
调包报错

### ISSUE THREAD

**Issue by Xuejin66** [caiyunapp/cyeva#52]
**描述BUG**
调用函数库时出现“DefinitionSyntaxError”报错

**复现方法**
from cyeva import Comparison,PrecipitationComparison,TemperatureComparison

**希望的结果**
调包无报错

**屏幕截图**
---------------------------------------------------------------------------
![image](https://github.com/caiyunapp/cyeva/assets/71546124/876dafc1-ace6-4cce-bf11-992b37b7a8e4)

**Comment by Clarmy** [comment]
你的 pint 包的版本是多少：`$ pip list | grep pint`

**Comment by Xuejin66** [comment]
好的，看起来没有问题了，谢谢~

**Comment by ringsaturn** [comment]
最新版本 v0.2.x 已经升级了关联的依赖到最新版本上，测试没问题了。
